### ISSUE TITLE
What is the status of fluxgraph

### ISSUE THREAD

**Issue by vallettea** [datablend/fluxgraph#5]
hello,

I am interested both in fluxgraph and in the tinkerpop stack so your project seems promizing. What is the current status of the project?
What is the benefit of fluxgraph?
thanks

**Comment by datablend** [comment]
Hi Alexandre,

Currently, the project is not being actively maintained. Let me know whether you would like to discuss a particular application of FluxGraph.

Davy

**Comment by vallettea** [comment]
ok, but is there a paper or an example that shows the way time is represented? Is there an alternative to just reading the code?

**Comment by vallettea** [comment]
ok i've found http://fr.slideshare.net/datablend/fluxgraph-a-timemachine-for-your-graphs
